[package]
name = "rmp-ipc"
version = "0.1.0"
authors = ["trivernis <trivernis@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.24"
rmp-serde = "0.15.4"
log = "0.4.14"

[dependencies.serde]
version = "1.0.125"
features = ["serde_derive"]

[dependencies.tokio]
version = "1.5.0"
features = ["net", "io-std", "io-util", "sync", "time"]


[dev-dependencies.tokio]
version = "1.5.0"
features = ["macros", "rt-multi-thread"]