[package]
name = "bromine"
version = "0.17.1"
authors = ["trivernis <trivernis@protonmail.com>"]
edition = "2018"
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/Trivernis/bromine/"
description = "A flexible ipc protocol (previously rmp-ipc)"

[lib]
bench=false

[[bench]]
name = "serialization_benchmark"
harness = false

[[bench]]
name = "deserialization_benchmark"
harness = false

[dependencies]
thiserror = "1.0.30"
tracing = "0.1.29"
lazy_static = "1.4.0"
typemap_rev = "0.1.5"
byteorder = "1.4.3"
async-trait = "0.1.52"
futures = "0.3.19"
num_enum = "0.5.6"
futures-core = "0.3.19"
rmp-serde = {version = "0.15.5", optional = true}
bincode = {version = "1.3.3", optional = true}
serde_json = {version = "1.0.73", optional = true}

[dependencies.serde]
optional = true
version = "1.0.132"
features = []

[dependencies.tokio]
version = "1.15.0"
features = ["net", "io-std", "io-util", "sync", "time"]

[dependencies.postcard]
version = "0.7.2"
optional = true
features = ["alloc"]

[dev-dependencies]
rmp-serde = "0.15.5"
crossbeam-utils = "0.8.5"

[dev-dependencies.serde]
version = "1.0.132"
features = ["serde_derive"]

[dev-dependencies.criterion]
version = "0.3.5"
features = ["async_tokio", "html_reports"]

[dev-dependencies.tokio]
version = "1.15.0"
features = ["macros", "rt-multi-thread"]

[features]
default = []
serialize = ["serde"]
serialize_rmp = ["serialize", "rmp-serde"]
serialize_bincode = ["serialize", "bincode"]
serialize_postcard = ["serialize", "postcard"]
serialize_json = ["serialize", "serde_json"]