[package]
name = "rmp-ipc"
version = "0.5.0"
authors = ["trivernis <trivernis@protonmail.com>"]
edition = "2018"
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/Trivernis/rmp-ipc"
description = "IPC using Rust MessagePack (rmp)"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.30"
rmp-serde = "0.15.4"
log = "0.4.14"
lazy_static = "1.4.0"
typemap_rev = "0.1.5"

[dependencies.serde]
version = "1.0.130"
features = ["serde_derive"]

[dependencies.tokio]
version = "1.12.0"
features = ["net", "io-std", "io-util", "sync", "time"]


[dev-dependencies.tokio]
version = "1.12.0"
features = ["macros", "rt-multi-thread"]